package edu.orangecoastcollege.cs273.dpham147.petprotector;

import android.net.Uri;

/**
 * Represents a Pet
 * A Pet will have a Name, Details, Phone number, Image,
 * and DB Generated unique ID
 */

public class Pet {

    private int mId;
    private String mName;
    private String mDetails;
    private String mPhone;
    private Uri mImageURI;

    public Pet()
    {

    }

    /**
     * Creates a Pet with all details filled
     * @param id unique ID generated by the database
     * @param name The pet's name
     * @param details Brief description of the pet
     * @param phone Contact number
     * @param imageURI URI to an image of the pet
     */
    public Pet(int id, String name, String details, String phone, Uri imageURI){
        mId = id;
        mName = name;
        mDetails = details;
        mPhone = phone;
        mImageURI = imageURI;
    }

    /**
     * Creates a pet without a unique ID
     * @param name The pet's name
     * @param details Brief description of the pet
     * @param phone Contact number
     * @param imageURI URI to an image of the pet
     */
    public Pet(String name, String details, String phone, Uri imageURI) {
        this(-1, name, details, phone, imageURI);
    }

    /**
     * Gets the unique ID of the pet
     * @return this pet's ID
     */
    public int getId()
    {
        return mId;
    }

    /**
     * Gets the name of this pet
     * @return This pet's name
     */
    public String getName()
    {
        return mName;
    }

    /**
     * Gets the description of the pet
     * @return This pet's description
     */
    public String getDetails()
    {
        return mDetails;
    }

    /**
     * Gets the contact number of this pet
     * @return This pet's contact number
     */
    public String getPhone()
    {
        return mPhone;
    }

    /**
     * Gets this pet's image URI
     * @return This pet's image URI
     */
    public Uri getImageURI()
    {
        return mImageURI;
    }

    /**
     * Changes the name of this pet
     * @param name This pet's new name
     */
    public void setName(String name)
    {
        mName = name;
    }

    /**
     * Changes the description of this pet
     * @param details The new description
     */
    public void setDetails(String details)
    {
        mDetails = details;
    }

    /**
     * Changes the contact number
     * @param phone The new contact number
     */
    public void setPhone(String phone)
    {
        mPhone = phone;
    }

    /**
     * Changes this pet's image URI
     * @param imageURI The new URI
     */
    public void setImageURI(Uri imageURI)
    {
        mImageURI = imageURI;
    }


    public String toString()
    {
        return ("Pet{" +
                "id: " + mId + ", name: " + mName +
        ", details: " + mDetails +
        ", phone:" + mPhone +
        ", imageURI:" + mImageURI);
    }
}
